version: '3'

services:
  skandigatebot:
    image: golang
    container_name: go
    volumes:
      - ".:/home/go/app"
    env_file:
      - ".env"
    command: go run main.go
    working_dir: /home/go/app
    depends_on:
      - skandigatebot-mysqldb
  skandigatebot-mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - "/etc/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./data/db/mysql:/var/lib/mysql"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
